

<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php echo $this->getChildHtml('product_review') ?> 
	
<div id="block-content" style="clear:both;width:1150px;overflow:hidden">
	
	<div style="clear:both;width:250px;float:right;position:relative;top:25px">
			
			
			
			
            <div style="width: 262px; margin-left: auto; margin-right: auto; height: 426px;" class="sticky-wrapper" id="undefined-sticky-wrapper"><div class="box-product-scroll">
                <h3><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h3>
                              <div class="product-box-prices">
                    

                        
    <div class="price-box">
                                            
                    <p class="old-price">
               
                <span class="price" id="old-price-131">
						  <?php
				 
					echo $this->getPriceHtml($_product, true); // Chamada padrão, retorna o preço + o HTML
				 
				?>

				  </span>
            </p>

                       
                    
    
        </div>
		<?php
			
				 
				   $vl =$_product->getPrice() /12; // Retorna o preço incial do produto (sem desconto, caso haver)
				
				    $vl2=number_format($vl,2,',','.');
				   
				
				
				?>
				

                    <p class="plots">em 12x de <span>R$ <?php echo $vl2?></span> sem juros</p><p class="avista"> </p>     
					</div>
          <input name="qty" id="qty" maxlength="12" value="1" title="Qtd" class="input-text form-control qty" type="hidden">
	    	<button type="button" title="Comprar" class="btn btn-lg btn-block btn-buy" onclick="productAddToCartForm.submit(this)"><span class="icon cart-bt"></span><span> Comprar</span></button>
	                                                                </div></div>
        
			
			
	</div>
<div class="block block-related" style="width:850px;">
    <div class="block-title">
      <header class="leo-header-box">
			<h2>
			OfertaSom indica: compre junto
			<span></span>
			</h2>
			<p></p>
			</header>
    </div>

    <div class="block-content">
        <p class="block-subtitle"><?php echo $this->__('Check items to add to the cart or') ?>&nbsp;<a href="#" onclick="selectAllRelated(this); return false;"><?php echo $this->__('select all') ?></a></p>
        <ol class="mini-products-list" id="block-related">
        <?php foreach($this->getItems() as $_item): ?>
            <li class="item">
                <?php if(!$_item->isComposite() && $_item->isSaleable()): ?>
                    <?php if (!$_item->getRequiredOptions()): ?>
                        <input type="checkbox" class="checkbox related-checkbox" id="related-checkbox<?php echo $_item->getId() ?>" name="related_products[]" value="<?php echo $_item->getId() ?>" />
                    <?php endif; ?>
                <?php endif; ?>
                <div class="product">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->escapeHtml($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(50) ?>" width="50" height="50" alt="<?php echo $this->escapeHtml($_item->getName()) ?>" /></a>
                    <div class="product-details">
					
					<p class="product-name product-related">
						<a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->escapeHtml($_item->getName()) ?></a></p>
						
							
                        <?php echo $this->getPriceHtml($_item, true, '-related') ?>
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
						<p class="plots" style="240px !important; text-align: center !important;margin-right:50px">
							em 12x de
							<span>R$78,42</span>
							sem juros
							</p>
                            <a style="240px !important; text-align: center !important;margin-left:40px" href="<?php echo $this->getAddToWishlistUrl($_item) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>
						
                    </div>
                </div>
            </li>
        <?php endforeach ?>
        </ol>
        <script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
    </div>

</div>
   
    

</div>
        <script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
    </div>
   <script type="text/javascript">
    //<![CDATA[
    $$('.related-checkbox').each(function(elem){
        Event.observe(elem, 'click', addRelatedToProduct)
    });

    var relatedProductsCheckFlag = false;
    function selectAllRelated(txt){
        if (relatedProductsCheckFlag == false) {
            $$('.related-checkbox').each(function(elem){
                elem.checked = true;
            });
            relatedProductsCheckFlag = true;
            txt.innerHTML="<?php echo $this->__('unselect all') ?>";
        } else {
            $$('.related-checkbox').each(function(elem){
                elem.checked = false;
            });
            relatedProductsCheckFlag = false;
            txt.innerHTML="<?php echo $this->__('select all') ?>";
        }
        addRelatedToProduct();
    }

    function addRelatedToProduct(){
        var checkboxes = $$('.related-checkbox');
        var values = [];
        for(var i=0;i<checkboxes.length;i++){
            if(checkboxes[i].checked) values.push(checkboxes[i].value);
        }
        if($('related-products-field')){
            $('related-products-field').value = values.join(',');
        }
    }
    //]]>
    </script>
</div>
   
    



