<?php
$code = $this->getMethodCode();
?>
<div class="ecommerce" id="payment_form_<?php echo $code ?>" style="display: none;">
    Após a conclusão do pedido, você será redirecionado à <span lang="EN-US" style="background-color: #FFFFFF;font-family: Gill Sans MT, Arial, Helvetica, sans-serif;color:#183C8E;font-size:18px;font-weight:bold;font-style:italic">REDECARD</span> para realizar o pagamento.
</div>